version: '3.9'

networks:
  nginx-php80:

services:
  # web server
  nginx-service:
    image: nginx:1.21.6-alpine
    container_name: nginx_container
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php80-service
    networks:
      - nginx-php80

  # php
  php80-service:
    container_name: php80_container
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    networks:
      - nginx-php80
